# see https://github.com/QuentinTorg/esphome_custom_components for source of truth

packages:
  feit_dimmer: !include
    file: package.feit_dimmer.yaml
    vars:
      device_name: upstairs-bathroom-dimmer
      friendly_name: Upstairs Bathroom
      restore_default_brightness: 'true'
      auto_off_enabled: 'true'
      auto_off_delay: 45min
