# see https://github.com/QuentinTorg/esphome_custom_components for source of truth

packages:
  base_config: !include
    file: package.feit_dimmer.yaml
    vars:
      device_name: upstairs-bathroom-sink-dimmer
      friendly_name: Upstairs Bathroom Sink Dimmer
