# see https://github.com/QuentinTorg/esphome_custom_components for source of truth

substitutions:
  device_name: unspecified-feit-dimmer
  friendly_name: "Unspecified Feit Dimmer Friendly Name"

  min_brightness: '0'
  max_brightness: '1000'

  # every time the light turns on, it will be restored to default
  # must pass true/false as strings
  restore_default_brightness: 'false'
  default_brightness: 100%

  # automatically turn off the light after specified time
  # must pass true/false as strings
  auto_off_enabled: 'false'
  auto_off_delay: 40min

  linked_ha_outlet_entity_id: unspecified


packages:
  base_config: !include
    file: package.base_config.yaml
    vars:
      device_name: "${device_name}"
      friendly_name: "${friendly_name}"
      comment: "${friendly_name} ESPHome Feit Dimmer"


# Feit dimmer uses esp8285 chip internally
esp8266:
  board: esp8285

# Disable serial logging by setting baud_rate to 0 because baud_rate/serial connection is used by tuyamcu
logger:
  level: DEBUG
  baud_rate: 0

uart:
  id: tuya_uart
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:
  uart_id: tuya_uart

light:
  - platform: "tuya"
    id: feit_dimmer
    name: "Dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: $min_brightness
    max_value: $max_brightness
    on_turn_on:
      then:
        - if:
            condition:
              lambda: 'return ${restore_default_brightness};'
            then:
              - light.control:
                  id: feit_dimmer
                  brightness: $default_brightness
        - if:
            condition:
              lambda: 'return ${auto_off_enabled};'
            then:
              - script.execute: feit_auto_off_timer
        - if:
            condition:
              and:
                - lambda: 'return (strcmp("${linked_ha_outlet_entity_id}", "unspecified") != 0);'
                - api.connected
            then:
              - logger.log: "Triggering home assistant switch on: ${linked_ha_outlet_entity_id}"
              - homeassistant.service:
                  service: homeassistant.turn_on # works for switch/light domains
                  data:
                    entity_id: $linked_ha_outlet_entity_id
    on_turn_off:
      then:
        - script.stop: feit_auto_off_timer
        - if:
            condition:
              and:
                - lambda: 'return (strcmp("${linked_ha_outlet_entity_id}", "unspecified") != 0);'
                - api.connected
            then:
              - logger.log: "Triggering home assistant switch off: ${linked_ha_outlet_entity_id}"
              - homeassistant.service:
                  service: homeassistant.turn_off # works for switch/light domains
                  data:
                    entity_id: $linked_ha_outlet_entity_id

script:
  - id: feit_auto_off_timer
    mode: restart # ensures re-invocation restarts the delay
    then:
      - delay: $auto_off_delay
      - light.turn_off: feit_dimmer
